@host=http://127.0.0.1:5001/api/v1/candidate

GET {{host}}


###
POST {{host}}/single
Content-Type: application/json

{
    "name":"Hari Kumar",
    "fatherName":"Narshingh Kumar",
    "motherName":"Reena Devi",
    "courseName":"NextJS Course Advanced"
}


### Delete all records
DELETE {{host}}