@host=http://127.0.0.1:5001/api/v1

GET {{host}} 

### 
GET {{host}}/compression 
x-no-compression

//Invalid path
###
GET {{host}}/fdsf 

###
POST  {{host}}

###
PATCH {{host}}

###
PUT {{host}}

###
DELETE  {{host}}

